/**
* VO 实体类
* This code is generated by FreeMarker
* created by shui
*/
public class user {

    private int user_id;

    private int org_id;

    private int dept_id;

    private tinyint status;

    private tinyint is_admin;

    private tinyint is_check_in_admin;

    private varchar remark;

    private datetime created_date;

    private datetime modified_date;

    private bigint sync_key;



    public void set User_id(int User_id()){
        this.User_id = User_id;
    }

    public int getUser_id() {
        return user_id;
    }


    public void set Org_id(int Org_id()){
        this.Org_id = Org_id;
    }

    public int getOrg_id() {
        return org_id;
    }


    public void set Dept_id(int Dept_id()){
        this.Dept_id = Dept_id;
    }

    public int getDept_id() {
        return dept_id;
    }


    public void set Status(tinyint Status()){
        this.Status = Status;
    }

    public tinyint getStatus() {
        return status;
    }


    public void set Is_admin(tinyint Is_admin()){
        this.Is_admin = Is_admin;
    }

    public tinyint getIs_admin() {
        return is_admin;
    }


    public void set Is_check_in_admin(tinyint Is_check_in_admin()){
        this.Is_check_in_admin = Is_check_in_admin;
    }

    public tinyint getIs_check_in_admin() {
        return is_check_in_admin;
    }


    public void set Remark(varchar Remark()){
        this.Remark = Remark;
    }

    public varchar getRemark() {
        return remark;
    }


    public void set Created_date(datetime Created_date()){
        this.Created_date = Created_date;
    }

    public datetime getCreated_date() {
        return created_date;
    }


    public void set Modified_date(datetime Modified_date()){
        this.Modified_date = Modified_date;
    }

    public datetime getModified_date() {
        return modified_date;
    }


    public void set Sync_key(bigint Sync_key()){
        this.Sync_key = Sync_key;
    }

    public bigint getSync_key() {
        return sync_key;
    }

}